ALTER TABLE audit_events
  DROP CONSTRAINT IF EXISTS audit_events_action_type_check;

ALTER TABLE audit_events
  DROP CONSTRAINT IF EXISTS audit_events_entity_type_check;

ALTER TABLE audit_events
  ADD CONSTRAINT audit_events_action_type_check CHECK (
    action_type IN (
      'DRAFT_STANDARD_CREATED',
      'DRAFT_STANDARD_UPDATED',
      'VERSION_CREATED',
      'REVIEW_CYCLE_CREATED',
      'REVIEW_CYCLE_UPDATED',
      'REVIEW_CYCLE_ACTIVATED',
      'REVIEW_CYCLE_CLOSED',
      'REVIEW_ASSIGNMENT_CREATED',
      'COMMENT_CREATED',
      'COMMENT_UPDATED',
      'COMMENT_DELETED',
      'POSITION_SUBMITTED',
      'POSITION_UPDATED',
      'COMMENT_STATUS_CHANGED',
      'SECRETARIAT_RESPONSE_UPDATED',
      'FILE_UPLOADED',
      'FILE_METADATA_CHANGED',
      'FILE_DELETED',
      'COMMITTEE_ORGANIZATION_CREATED',
      'COMMITTEE_ORGANIZATION_UPDATED',
      'COMMITTEE_PERSON_CREATED',
      'COMMITTEE_PERSON_UPDATED',
      'COMMITTEE_ROLE_ASSIGNMENT_CREATED',
      'COMMITTEE_ROLE_ASSIGNMENT_UPDATED',
      'SUBCOMMITTEE_CREATED',
      'SUBCOMMITTEE_UPDATED',
      'NEWS_ITEM_CREATED',
      'NEWS_ITEM_UPDATED',
      'NEWS_ITEM_PUBLISHED',
      'NEWS_ITEM_UNPUBLISHED',
      'PUBLIC_DOCUMENT_CREATED',
      'PUBLIC_DOCUMENT_UPDATED',
      'PUBLIC_DOCUMENT_PUBLISHED',
      'PUBLIC_DOCUMENT_UNPUBLISHED',
      'MEETING_RECORD_CREATED',
      'MEETING_RECORD_UPDATED',
      'MEETING_RECORD_PUBLISHED',
      'MEETING_RECORD_UNPUBLISHED',
      'APPROVED_STANDARD_CREATED',
      'APPROVED_STANDARD_UPDATED',
      'APPROVED_STANDARD_PUBLISHED',
      'APPROVED_STANDARD_UNPUBLISHED',
      'LEGACY_CONTENT_INVENTORY_CREATED',
      'LEGACY_CONTENT_INVENTORY_UPDATED'
    )
  );

ALTER TABLE audit_events
  ADD CONSTRAINT audit_events_entity_type_check CHECK (
    entity_type IN (
      'DRAFT_STANDARD',
      'DRAFT_STANDARD_VERSION',
      'REVIEW_CYCLE',
      'REVIEW_ASSIGNMENT',
      'REVIEW_COMMENT',
      'PARTICIPANT_POSITION',
      'VERSION_FILE',
      'COMMITTEE_ORGANIZATION',
      'COMMITTEE_PERSON',
      'COMMITTEE_ROLE_ASSIGNMENT',
      'SUBCOMMITTEE',
      'NEWS_ITEM',
      'PUBLIC_DOCUMENT',
      'MEETING_RECORD',
      'APPROVED_STANDARD',
      'LEGACY_CONTENT_INVENTORY'
    )
  );
